name: Execute SSM Command

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ttp:
        description: 'TTP ID to execute'
        required: true
        default: 'T1558.003'

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  

    - name: Execute SSM Command
      run: |
        TTP=${{ github.event.inputs.ttp }}
        aws ssm send-command \
          --document-name "AWS-RunPowerShellScript" \
          --targets "Key=instanceids,Values=i-0f1f5556800682384" \
          --parameters '{"commands":["Start-Process powershell.exe -ArgumentList \"-NoProfile -Command \"Invoke-AtomicTest '${TTP}' > output.log 2>&1\"\" -WindowStyle Hidden"]}'
